CREATE CONSTRAINT material_canonical_label_unique IF NOT EXISTS
FOR (n:Material) REQUIRE n.canonical_label IS UNIQUE;
CREATE CONSTRAINT process_canonical_label_unique IF NOT EXISTS
FOR (n:Process) REQUIRE n.canonical_label IS UNIQUE;
CREATE CONSTRAINT equipment_canonical_label_unique IF NOT EXISTS
FOR (n:Equipment) REQUIRE n.canonical_label IS UNIQUE;
CREATE CONSTRAINT property_canonical_label_unique IF NOT EXISTS
FOR (n:Property) REQUIRE n.canonical_label IS UNIQUE;
CREATE CONSTRAINT experiment_canonical_label_unique IF NOT EXISTS
FOR (n:Experiment) REQUIRE n.canonical_label IS UNIQUE;
CREATE CONSTRAINT publication_canonical_label_unique IF NOT EXISTS
FOR (n:Publication) REQUIRE n.canonical_label IS UNIQUE;
CREATE CONSTRAINT expert_canonical_label_unique IF NOT EXISTS
FOR (n:Expert) REQUIRE n.canonical_label IS UNIQUE;
CREATE CONSTRAINT facility_canonical_label_unique IF NOT EXISTS
FOR (n:Facility) REQUIRE n.canonical_label IS UNIQUE;
CREATE CONSTRAINT condition_canonical_label_unique IF NOT EXISTS
FOR (n:Condition) REQUIRE n.canonical_label IS UNIQUE;
CREATE CONSTRAINT country_canonical_label_unique IF NOT EXISTS
FOR (n:Country) REQUIRE n.canonical_label IS UNIQUE;
CREATE CONSTRAINT claim_canonical_label_unique IF NOT EXISTS
FOR (n:Claim) REQUIRE n.canonical_label IS UNIQUE;
CREATE CONSTRAINT document_document_id_unique IF NOT EXISTS
FOR (n:Document) REQUIRE n.document_id IS UNIQUE;
